repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.7  # или последняя версия
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]  # автофикс + показывает, что были изменения
#        args: [--fix, --exit-non-zero-on-fix]  # автофикс + показывает, что были изменения