version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.47.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.9.6
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml
      - ./data/loki:/loki/data
    networks:
      - monitoring

  alloy:
    image: grafana/alloy:v1.1.0
    container_name: alloy
    volumes:
      - ./config/alloy-config.river:/etc/alloy/config.river
      # Монтируем лог-файл или всю папку с логами
      - C:/Users/evgeniy.butkov/PycharmProjects/parse_flashscore/logs:/logs:ro
    networks:
      - monitoring
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - monitoring
    depends_on:
      - prometheus
      - loki

networks:
  monitoring:
    driver: bridge